import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from '../components/Login'
import Container from 'react-bootstrap/Container'

const Home: NextPage = () => {
  // localStorage.getItem('in')
  // if (localStorage.getItem('in') == 'false'){
  //   alert('hello')
  // }
  return (
    // <div className={styles.container}>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Login></Login>
      </Container>

    // </div>
  )
}

export default Home
