import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from '../components/Login'
import Container from 'react-bootstrap/Container'
import { signIn, signOut, useSession } from "next-auth/client"

const Home: NextPage = () => {
  // let e3 = localStorage.getItem('in')
  // if (e3 == 'true' ){
  //   alert('hello')
  // }
  return (
    <div className={styles.container}>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Login></Login>
      </Container>

    </div>
  )
}

// export async function getStaticProps(context: any) {
//   // let xc1= localStorage.getItem('login')




//   // if (xc1 == 'yes') {
//     return {
//       redirect: {
//         destination: '/users/dashboard/DashboardU',
//         permanent: false
//       }
//     }
//   // }
// }

export default Home
